#!/bin/bash

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}
	pct=used/total*100
    if (pct == 0){
	    printf("%.f%%\n", pct)
    }
	# full text
	#printf("%.1fG/%.1fG (%.f%%)\n", used, total, pct)
	# medium text
	printf("%.1fG/%.1fG\n", used, total)
	# short text
	# color
	if (pct > 90) {
		print("#F97F81\n")
	} else if (pct > 70) {
		print("#D3876D\n")
	} else if (pct > 50) {
		print("#ECCA85\n")
	}
}
' /proc/meminfo
